name: blank_flutter_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Splashing
  flutter_native_splash:
  # Localization
  easy_localization:
  # State management.
  flutter_bloc:
  # Code generation for immutable classes (cubit & retrofit).
  freezed:
  freezed_annotation:
  # Dependency injection.
  get_it:
  # Classes and helper functions that support JSON code generation.
  json_annotation:
  json_serializable:
  # Networking
  dio:
  retrofit:
  retrofit_generator:
  pretty_dio_logger:
  flutter_secure_storage:
  # UI
  flutter_screenutil:
  cached_network_image:
  flutter_svg:
  lottie:
  shimmer:
  # Data Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: # dart run build_runner build
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
#  fonts:
#    - family: Kanit
#      fonts:
#        - asset: assets/fonts/Kanit/Kanit-Black.ttf
#        - asset: assets/fonts/Kanit/Kanit-BlackItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
#        - asset: assets/fonts/Kanit/Kanit-BoldItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-ExtraBold.ttf
#        - asset: assets/fonts/Kanit/Kanit-ExtraBoldItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-ExtraLight.ttf
#        - asset: assets/fonts/Kanit/Kanit-ExtraLightItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Italic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Light.ttf
#        - asset: assets/fonts/Kanit/Kanit-LightItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
#        - asset: assets/fonts/Kanit/Kanit-MediumItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
#        - asset: assets/fonts/Kanit/Kanit-SemiBold.ttf
#        - asset: assets/fonts/Kanit/Kanit-SemiBoldItalic.ttf
#        - asset: assets/fonts/Kanit/Kanit-Thin.ttf
#        - asset: assets/fonts/Kanit/Kanit-ThinItalic.ttf
